---
apiVersion: v1
kind: Pod
metadata:
  name: kk6gpv-bus-wx
spec:
  restartPolicy: OnFailure
  containers:
    - name: application
      image: areed145/kk6gpv-bus-wx:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 4000
      livenessProbe:
        tcpSocket:
          port: 4000
        initialDelaySeconds: 60
        periodSeconds: 10
        failureThreshold: 6
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
