---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ GITHUB_REPOSITORY }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ${{ GITHUB_REPOSITORY }}
  template:
    metadata:
      labels:
        name: ${{ GITHUB_REPOSITORY }}
    spec:
      containers:
        - name: application
          image: areed145/${{ GITHUB_REPOSITORY }}:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
