site_name: kk6gpv-bus-wx
site_description: 'Documentation for kk6gpv-bus-wx component of Coconut Barometer site'
site_author: 'Adam Reeder'
docs_dir: docs/
repo_name: 'areed145/kk6gpv-bus-wx'
repo_url: 'https://github.com/areed145/kk6gpv-bus-wx'
nav:
    - Home: index.md
theme:
  name: 'material'
  font:
    text: Ubuntu
    code: Ubuntu Mono
  plugins:
    - search
    - mkdocstrings:
        handlers:
            python:
                setup_commands:
                    - import sys
                    - sys.path.append("src/kk6gpv-bus-wx")
        watch:
            - src/kk6gpv-bus-wx
